export const ADD_CART_REQUEST = "ADD_CART_REQUEST"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_FAIL = "ADD_CART_FAIL"

export const SUBTRACT_CART_REQUEST = "SUBTRACT_CART_REQUEST"
export const SUBTRACT_CART_SUCCESS = "SUBTRACT_CART_SUCCESS"
export const SUBTRACT_CART_FAIL = "SUBTRACT_CART_FAIL"

export const REMOVE_CART_REQUEST = "REMOVE_CART_REQUEST"
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"
export const REMOVE_CART_FAIL = "REMOVE_CART_FAIL"